### ISSUE TITLE
could provide detailed README documentation or example cases?

### ISSUE THREAD

**Issue by BioLaoXu** [IdoSpringer/ERGO#3]
Hi dear team 
ERGO has the highest accuracy of any predictive software I've ever seen in some related article,i have tested netTCR，but the prediction accuracy ~30% for my data, so i want use ERGO predict TCR and pepitide binding ,i think ERGO could provide a higher prediction accuracy,but there is no example and  detailed README documentation for ERGO.py

**Comment by GiancarloCroce** [comment]
Hi,
as @xf78 pointed out, your tool has very high predictive power and can be extremely useful to the scientific community. However, it is difficult to use it since detailed README documentation is missing. Could you please upload it?
As a side note, I tried to re-do the plots of Table 4 of your biorxiv paper using the functions of the plots.py script, but it requires the folder 'final_results' which is not in the github repository. It would be possible to upload it as well? 
Thank you!

**Comment by IdoSpringer** [comment]
Hi, I'm sorry for the late reply. This is mainly the research repository, so the code has to be modified in order to use ERGO as a public predictive tool. I will try to do it soon (and update the README). Meanwhile, you can use our webtool at http://tcr.cs.biu.ac.il/.
The final_results directory contains datasets and trained model parameters. It is to heavy to be uploaded to github. I will try to solve it when modifying this repository.

**Comment by IdoSpringer** [comment]
The readme was updated in the other repository available at https://github.com/louzounlab/ERGO
